### ISSUE TITLE
Can we allow use of array reduce?

### ISSUE THREAD

**Issue by petervdn** [mediamonks/eslint-config#146]
Why do we have the `unicorn/no-array-reduce` rule exactly? I don't really agree that we promote this 

```
let total = 0;
for(const item in items) {
   total += item.price;
}
```
over

```
const total = items.reduce((sum, item) => sum + item.price, 0)
```

**Comment by ThaNarie** [comment]
@petervdn You could:
- read the docs: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-reduce.md
- then read the related conversations around it that are linked.
- then read the examples they gave.

And if you disagree with that, or are unsure about the added value of the rule, then you can counter those arguments with your own arguments/examples :) That way other people can way in on those as well.

I even think your example is in the "pass" list, but it might not being recognised that way because of the object notation in it.

**Comment by petervdn** [comment]
Apart from the spread performance issue, which imho is something you can simply choose *not* to do, the argument "hard to read" (with the added explanation being "[mutes thread](https://twitter.com/jaffathecake/status/1213077702300852224))" is not something i agree with. Someone who never used `Array.map` (or the other array functions) before could say the same thing about that.

My main reason is that I find it very ugly to initialise a variable with a value that you already know is not the value that it needs to be (and also therefor not being able to define it as a `const`), especially when the `.reduce` syntax is imho very clean, minimal and clear.

Btw my example above is not representative of my normal `.reduce` usage :)

**Comment by leroykorterink** [comment]
Readability is subjective (hence we're using `prettier`) and I completely agree that `Array.reduce` is the right syntax for the example that you gave @petervdn, but most code I see that uses `Array.reduce` isn't usually that simple.

I see that `Array.reduce` was used "incorrectly" quite often in the projects I've been working on recently and this has changed my opinion on keeping this rule, it's easy to skip over small issues like this when reviewing code while the performance impact can be quite severe when working on *large* lists.

<img width="1154" alt="image" src="https://github.com/mediamonks/eslint-config/assets/5376407/343b5fe0-4640-4dd4-bf38-62db28a6c820">

Strict immutability is 100% slower, this is a pattern I often see in reduce callback functions because it's encouraged to write pure functions (functions that do not have side effects/modify parameters). The equivalent example in the `for...of` loop is not common as I think most people would've written it like the fastest code example. 

A few months back I actually thought we should disable the rule, but I think there's little downside to keeping it enabled while it may prevent incorrect usages of `Array.reduce`
